# Generated by Django 5.1.6 on 2025-04-20 05:11

import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_id',
            field=models.CharField(default=purchase.models.generate_po_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
