# Generated by Django 5.1.6 on 2025-04-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='varianttype',
            unique_together=set(),
        ),
    ]
