# Generated by Django 5.1.6 on 2025-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_bankpaymentsmonitor_cashmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Both', 'Both')], max_length=20),
        ),
    ]
