# Generated by Django 5.1.6 on 2025-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchasepayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='bank_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='cash_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
