# Generated by Django 5.1.6 on 2025-04-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_purchasepayment_bank_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianttype',
            name='options',
        ),
        migrations.RemoveField(
            model_name='varianttype',
            name='purchase_item_name',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='variant_types',
            field=models.ManyToManyField(blank=True, related_name='purchase_items', to='purchase.varianttype'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='purchase_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseitem'),
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='purchase.varianttype')),
            ],
        ),
        migrations.CreateModel(
            name='VariantCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='purchase.purchaseitem')),
                ('options', models.ManyToManyField(to='purchase.variantoption')),
            ],
        ),
    ]
