# Generated by Django 5.1.6 on 2025-04-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('purchase', '0012_remove_varianttype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='varianttype',
            unique_together={('title', 'company', 'branch')},
        ),
    ]
